prerelease: true
categories:
  - title: ":rocket: Features"
    labels: 
      - feature
      - improvement
  - title: ":bug: Bug Fixes"
    label: bug
  - title: ":warning: Security"
    label: security
  - title: ":construction: Maintenance"
    label: chore
  - title: ":bangbang: Breaking changes"
    label: breaking
  - title: ":speech_balloon: Documentation"
    label: documentation

template: |
  ## Changes

  $CHANGES

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: '/GOC-(\d{1,5})/gi'
    replace: 'https://github.com/goci-io/goci-community/issues/$1'
