name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels: 
      - feature
      - feat
      - improvement
      - refactor
      - perf
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bug
  - title: 🧰 Maintenance
    labels: 
      - chore
      - ci
  - title: 🧰 Breaking changes
    label: break
  - title: Reverted
    label: revert
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
