categories:
  - title: :rocket: Features
    labels: 
      - feature
      - feat
      - improvement
      - refactor
      - perf
  - title: :bug: Bug Fixes
    labels:
      - fix
      - bug
  - title: :construction: Maintenance
    labels: 
      - chore
      - ci
  - title: :bangbang: Breaking changes
    label: break
  - title: :arrow_upper_right: Reverted
    label: revert
template: |
  ## Changes

  $CHANGES

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
